# Generated by Django 4.2.4 on 2023-08-26 23:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edushare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='Contenu',
        ),
        migrations.AlterField(
            model_name='cours',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cours',
            name='ecole',
            field=models.CharField(max_length=255, verbose_name='École ou université'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='prix',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix du cours'),
        ),
        migrations.AddField(
            model_name='cours',
            name='contenu',
            field=models.FileField(blank=True, null=True, upload_to='cours_content/'),
        ),
    ]
