# Generated by Django 4.2.4 on 2023-08-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edushare', '0002_remove_cours_contenu_alter_cours_auteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cours_achetes',
            field=models.ManyToManyField(blank=True, related_name='users_achetes', to='edushare.cours', verbose_name='Cours achetés'),
        ),
        migrations.AddField(
            model_name='user',
            name='cours_telecharges',
            field=models.ManyToManyField(blank=True, related_name='users_telecharges', to='edushare.cours', verbose_name='Cours téléchargés'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Université/École'),
        ),
    ]
