# Generated by Django 4.2.4 on 2023-08-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edushare', '0005_alter_commentaires_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
