# Generated by Django 4.2.4 on 2023-08-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edushare', '0007_alter_cours_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='titre',
            field=models.CharField(max_length=255),
        ),
    ]
